Student Record App V2/Models/DataAccess/AcademicRecord.cs
using System;
using System.Collections.Generic;

namespace Lab6.Models.DataAccess
{
    public partial class AcademicRecord
    {
        public string CourseCode { get; set; }
        public string StudentId { get; set; }
        public int? Grade { get; set; }

        public virtual Course CourseCodeNavigation { get; set; }
        public virtual Student Student { get; set; }
    }
}

Student Record App V2/Controllers/AcademicRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab6.Models.DataAccess;
using Lab6.Models;
using Microsoft.AspNetCore.Http;

namespace Lab6.Controllers
{
    public class AcademicRecordsController : Controller
    {
        private readonly StudentRecordContext _context;

        public AcademicRecordsController(StudentRecordContext context)
        {
            _context = context;
        }

        // GET: AcademicRecords
        public async Task<IActionResult> Index(string sort)
        {
            ViewData["sort"] = sort;

            var StudentRecordContext = _context.AcademicRecord.Include(a => a.CourseCodeNavigation).Include(a => a.Student);
            var sortedRecords = StudentRecordContext.ToArray();
            if (sort == "course")
            {
                sortedRecords = StudentRecordContext.OrderBy(r => r.CourseCodeNavigation.Title).ToArray();
            }
            else if (sort == "student")
            {
                sortedRecords = StudentRecordContext.OrderBy(r => r.Student.Name).ToArray();
            }
            else if (sort == "grade")
            {
                sortedRecords = StudentRecordContext.OrderBy(r => r.Grade).ToArray();
            }
            if (HttpContext.Session.GetString("SortOrder") == null || HttpContext.Session.GetString("SortOrder") == "Descending")
            {
                HttpContext.Session.SetString("SortOrder", "Ascending");
            }
            else
            {
                HttpContext.Session.SetString("SortOrder", "Descending");
                sortedRecords = sortedRecords.Reverse().ToArray();
            }
            return View(sortedRecords);
        }

        // GET: AcademicRecords/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academicRecord = await _context.AcademicRecord
                .Include(a => a.CourseCodeNavigation)
                .Include(a => a.Student)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (academicRecord == null)
            {
                return NotFound();
            }

            return View(academicRecord);
        }

        // GET: AcademicRecords/Create
        public IActionResult Create()
        {
            var courses = (from a in _context.Course select new { Code = a.Code, Title = a.Code + " - " + a.Title }).ToList();
            ViewData["CourseCode"] = new SelectList(courses,"Code", "Title");
            
            var students  = (from b in _context.Student select new { Id = b.Id, Name = b.Id + " - " + b.Name }).ToList();
            ViewData["StudentId"] = new SelectList(students, "Id", "Name");
            return View();
        }

        // POST: AcademicRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseCode,StudentId,Grade")] AcademicRecord academicRecord)
        {
            if (ModelState.IsValid)
            {
                var exists = (from e in _context.AcademicRecord where string.Compare(e.StudentId, academicRecord.StudentId) == 0 && string.Compare(e.CourseCode, academicRecord.CourseCode) == 0 select e).FirstOrDefault<AcademicRecord>();

                if(exists == null)
                {
                    _context.Add(academicRecord);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("CourseCode", "The student has already had an academic record for this course");
                }
            }
            var courses = (from a in _context.Course select new { Code = a.Code, Title = a.Code + " - " + a.Title }).ToList();
            ViewData["CourseCode"] = new SelectList(courses, "Code", "Title");

            var students = (from b in _context.Student select new { Id = b.Id, Name = b.Id + " - " + b.Name }).ToList();
            ViewData["StudentId"] = new SelectList(students, "Id", "Name");
            return View(academicRecord);
        }

        // GET: AcademicRecords/Edit/5
        public async Task<IActionResult> Edit(string StudentId, string courseCode)
        {
            if (StudentId == null || courseCode == null)
            {
                return NotFound();
            }
            var academicRecord = (from ar in _context.AcademicRecord.Include(a => a.CourseCodeNavigation).Include(a => a.Student)
                                  where ar.CourseCode == courseCode && ar.StudentId == StudentId
                                  select ar).FirstOrDefault<AcademicRecord>();
            if (academicRecord == null)
            {
                return NotFound();
            }
            return View(academicRecord);
        }

        // POST: AcademicRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AcademicRecord academicRecord)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(academicRecord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AcademicRecordExists(academicRecord.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseCode"] = new SelectList(_context.Course, "Code", "Code", academicRecord.CourseCode);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", academicRecord.StudentId);
            return View(academicRecord);
        }

        public async Task<IActionResult> EditAll()
        {
            var records = _context.AcademicRecord.Include(a => a.CourseCodeNavigation).Include(a => a.Student);
            var sortedRecords = records.ToArray();
            string sort = HttpContext.Request.Query["sort"].ToString();
            if (sort == "course")
            {
                sortedRecords = records.OrderBy(r => r.CourseCodeNavigation.Title).ToArray();
            }
            else if (sort == "student")
            {
                sortedRecords = records.OrderBy(r => r.Student.Name).ToArray();
            }
            else
            {
                sortedRecords = records.OrderBy(r => r.Grade).ToArray();
            }
            if (HttpContext.Session.GetString("SortOrder") == null || HttpContext.Session.GetString("SortOrder") == "Descending")
            {
                HttpContext.Session.SetString("SortOrder", "Ascending");
            }
            else
            {
                HttpContext.Session.SetString("SortOrder", "Descending");
                sortedRecords = sortedRecords.Reverse().ToArray();
            }
            return View(sortedRecords);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAll(AcademicRecord[] academicRecords)
        {
            if (ModelState.IsValid)
            {
                foreach (AcademicRecord record in academicRecords)
                {
                    _context.Update(record);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(academicRecords);
        }

        // GET: AcademicRecords/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academicRecord = await _context.AcademicRecord
                .Include(a => a.CourseCodeNavigation)
                .Include(a => a.Student)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (academicRecord == null)
            {
                return NotFound();
            }

            return View(academicRecord);
        }

        // POST: AcademicRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var academicRecord = await _context.AcademicRecord.FindAsync(id);
            _context.AcademicRecord.Remove(academicRecord);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AcademicRecordExists(string id)
        {
            return _context.AcademicRecord.Any(e => e.StudentId == id);
        }
    }
}

Student Record App V2/Views/AcademicRecords/Create.cshtml
@model Lab6.Models.DataAccess.AcademicRecord

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AcademicRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseCode" class="control-label"></label>
                <select asp-for="CourseCode" class="form-control" asp-items="ViewBag.CourseCode"></select>
                <span asp-validation-for="CourseCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Student Record App V2/Views/AcademicRecords/Delete.cshtml
@model Lab6.Models.DataAccess.AcademicRecord

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AcademicRecord</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseCodeNavigation.Code)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CourseCode" />
        <input type="hidden" asp-for="StudentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Student Record App V2/Views/AcademicRecords/Details.cshtml
@model Lab6.Models.DataAccess.AcademicRecord

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AcademicRecord</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseCodeNavigation.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Student Record App V2/Views/AcademicRecords/Edit.cshtml
@model Lab6.Models.DataAccess.AcademicRecord

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AcademicRecord</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseCode" />
            <input type="hidden" asp-for="StudentId" />
            <dl class="row">
                <dt class="col-md-2">
                    Course   
                </dt>
                <dd class="col-md-10">
                    @(Model.CourseCode + " - " + Model.CourseCodeNavigation.Title)
                </dd>
            </dl>
            <dl class="row">
                <dt class="col-md-2">
                    Student  
                </dt>
                <dd class="col-md-10">
                    @(Model.StudentId + " - " + Model.Student.Name)
                </dd>
            </dl>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Student Record App V2/Views/AcademicRecords/EditAll.cshtml
@model Lab6.Models.DataAccess.AcademicRecord[]

@{
    ViewData["Title"] = "EditAll";
}

<h1>EditAll</h1>

<input type="hidden" name="sort" value="@ViewData["sort"]" />
<form asp-action="EditAll" asp-controller="AcademicRecords" method="POST">
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-controller="AcademicRecords" asp-action="EditAll" asp-route-sort="course">Course</a>
                </th>
                <th>
                    <a asp-controller="AcademicRecords" asp-action="EditAll" asp-route-sort="student">Student</a>
                </th>
                <th>
                    <a asp-controller="AcademicRecords" asp-action="EditAll" asp-route-sort="grade">Grade</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Length; i++)
            {
                <tr>
                    <td>
                        <span asp-for="@Model[i].CourseCodeNavigation.Code">@Model[i].CourseCode - @Model[i].CourseCodeNavigation.Title</span>
                        <input type="hidden" asp-for="@Model[i].CourseCode" />
                    </td>
                    <td>
                        <span asp-for="@Model[i].Student.Name">@Model[i].StudentId - @Model[i].Student.Name</span>
                        <input type="hidden" asp-for="@Model[i].StudentId" />
                    </td>
                    <td>
                        <input type="text" class="form-control" style="width: 60px" asp-for="@Model[i].Grade" value="@Model[i].Grade" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <input type="submit" value="Save" class="btn btn-primary" />
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>

</form>

Student Record App V2/Views/AcademicRecords/Index.cshtml
@model Lab6.Models.DataAccess.AcademicRecord[]
@using Lab6.Models.DataAccess;

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <input type="hidden" name="sort" value="@ViewData["sort"]" />
    <thead>
        <tr>
            <th>
                <a asp-controller="AcademicRecords" asp-action="Index" asp-route-sort="course">Course</a>
            </th>
            <th>
                <a asp-controller="AcademicRecords" asp-action="Index" asp-route-sort="student">Student</a>
            </th>
            <th>
                <a asp-controller="AcademicRecords" asp-action="Index" asp-route-sort="grade">Grade</a>
            </th>
            <th><a asp-action="EditAll">Edit All</a></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseCodeNavigation.Code) - @Html.DisplayFor(modelItem => item.CourseCodeNavigation.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.Id) - @Html.DisplayFor(modelItem => item.Student.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td>
                    @{
                        var data = new Dictionary<string, string> { { "studentId", item.StudentId }, { "courseCode", item.CourseCode } };
                    }
                    <a asp-action="Edit" asp-route-studentId="@item.StudentId" asp-route-courseCode="@item.CourseCode">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>